// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import config = require("./src/config/config");
const { defineConfig } = require("prisma/config");
export = defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: config.DATABASE_URL,
  },
});
